export const ADD_NOTIFICATION = "ADD_NOTIFICATION";
export const DELETE_NOTIFICATION = "DELETE_NOTIFICATION";
export const SET_ENTITY = "SET_ENTITY";
export const ADD_ENTITY = "ADD_ENTITY";
export const UPDATE_ENTITY_ARRAY = "UPDATE_ENTITY_ARRAY";
export const UPDATE_ENTITY_OBJECT = "UPDATE_ENTITY_OBJECT";
export const DELETE_ENTITY = "DELETE_ENTITY";

export const CLEAR_STATE = "CLEAR_STATE";
export const SET_PIZZA_TO_CHANGE = "SET_PIZZA_TO_CHANGE";
